/* DO NOT EDIT THIS FILE
 *
 * Copyright (c) 2005 Borland Software Corporation. All Rights Reserved.
 *
 */

package com.borland.dx.util;

public class ResIndex {
  public static final int MissingDataSource                        = 0;
  public static final int InvalidStart                             = 1;
  public static final int MustSetProp                              = 2;
  public static final int PropertyNotHandled                       = 3;
  public static final int DataSourceMustBeUnique                   = 4;
  public static final int PropNotFound                             = 5;
  public static final int MethodNotFound                           = 6;
}
