/* DO NOT EDIT THIS FILE
 *
 * Copyright (c) 2005 Borland Software Corporation. All Rights Reserved.
 *
 */

package com.borland.dx.swing;

public class ResIndex {
  public static final int Password                                 = 0;
  public static final int OKBtn                                    = 1;
  public static final int CancelBtn                                = 2;
  public static final int UserName                                 = 3;
}
