/* DO NOT EDIT THIS FILE
 *
 * Copyright (c) 2005 Borland Software Corporation. All Rights Reserved.
 *
 */

package com.borland.dx.text;

public class ResIndex {
  public static final int FormatError                              = 0;
  public static final int BooleanBad                               = 1;
  public static final int False                                    = 2;
  public static final int True                                     = 3;
  public static final int BytePrecisionBad                         = 4;
  public static final int ShortPrecisionBad                        = 5;
  public static final int ParseNotSupported                        = 6;
  public static final int TrueFalsePattern                         = 7;
  public static final int MustBeVariant                            = 8;
  public static final int JDKErrMsg                                = 9;
  public static final int ParseError                               = 10;
}
