/* DO NOT EDIT THIS FILE
 *
 * Copyright (c) 2005 Borland Software Corporation. All Rights Reserved.
 *
 */

package com.borland.dx.text;
import com.borland.jb.util.*;

public class ResTable extends StringArrayResourceBundle {
  public ResTable() {
    strings = new String[] {
      "Format error:  {0}",
      "Cannot format given Object as a Boolean",
      "false",
      "true",
      "Number must be between -128 and 127",
      "Number must be between -32768 and 32767",
      "This formatter does not support this version of parse",
      "true;false",
      "ItemFormatter: expected Variant as parameter",
      "JDK error message",
      "Error in parsing string.  Expecting this format: {0}",
    };
  }
}
