/* DO NOT EDIT THIS FILE
 *
 * Copyright (c) 2005 Borland Software Corporation. All Rights Reserved.
 *
 */

package com.borland.dx.sql.metadata;

public class ResIndex {
  public static final int BadFieldlist                             = 0;
  public static final int InvalidColumnType                        = 1;
  public static final int NotImplemented                           = 2;
}
