// DO NOT EDIT THIS FILE
// Copyright (c) 2005, Borland Software Corporation. All Rights Reserved.
// version 3

package com.borland.dbswing.editors;

public class Res extends java.util.ResourceBundle {

  protected Object handleGetObject(String key) { return null; }
  public java.util.Enumeration getKeys()       { return null; }

  private static final Res bundle = getBundle();

  private static Res getBundle() {
    try {
      return (Res)getBundle("com.borland.dbswing.editors.Res");
    } catch (Exception e) {
      return new Res();
    }
  }

//------------------------------------------//
  protected    String _res_BI_German = "German";
  public static final String  _BI_German = bundle._res_BI_German;
  protected    String _res_BI_Spanish = "Spanish";
  public static final String  _BI_Spanish = bundle._res_BI_Spanish;
  protected    String _res_BI_Italian = "Italian";
  public static final String  _BI_Italian = bundle._res_BI_Italian;
  protected    String _res_BI_Greek = "Greek";
  public static final String  _BI_Greek = bundle._res_BI_Greek;
  protected    String _res_BI_Chinese_China = "Chinese (China)";
  public static final String  _BI_Chinese_China = bundle._res_BI_Chinese_China;
  protected    String _res_BI_Russian = "Russian";
  public static final String  _BI_Russian = bundle._res_BI_Russian;
  protected    String _res_BI_Turkish = "Turkish";
  public static final String  _BI_Turkish = bundle._res_BI_Turkish;
  protected    String _res_BI_Korean = "Korean";
  public static final String  _BI_Korean = bundle._res_BI_Korean;
  protected    String _res_BI_French = "French";
  public static final String  _BI_French = bundle._res_BI_French;
  protected    String _res_BI_Chinese_Taiwan = "Chinese (Taiwan)";
  public static final String  _BI_Chinese_Taiwan = bundle._res_BI_Chinese_Taiwan;
  protected    String _res_BI_default = "<default>";
  public static final String  _BI_default = bundle._res_BI_default;
  protected    String _res_BI_Croatian = "Croatian";
  public static final String  _BI_Croatian = bundle._res_BI_Croatian;
  protected    String _res_BI_Norwegian = "Norwegian";
  public static final String  _BI_Norwegian = bundle._res_BI_Norwegian;
//==========================================//

  public static String findString(String id) {
    try {
      return (String)Res.class.getDeclaredField("_" + id).get(null);
    } catch (Exception any) {
      return null;
    }
  }
}
