/* DO NOT EDIT THIS FILE
 *
 * Copyright (c) 2005 Borland Software Corporation. All Rights Reserved.
 *
 */

package com.borland.jb.io;

public class ResIndex {
  public static final int ErrorCode                                = 0;
  public static final int ChainedException                         = 1;
  public static final int ExceptionChain                           = 2;
  public static final int InvalidMarkReset                         = 3;
}
