/* DO NOT EDIT THIS FILE
 *
 * Copyright (c) 2005 Borland Software Corporation. All Rights Reserved.
 *
 */

package com.borland.jb.io;
import com.borland.jb.util.*;

public class ResTable extends StringArrayResourceBundle {
  public ResTable() {
    strings = new String[] {
      "See {0} error code:  BASE+{1}",
      "Chained exception:",
      "Chain of 2 or more Exceptions occurred",
      "Resetting to invalid mark",
    };
  }
}
